---
title: "Using R"
output: html_document
---

# Using R

R is available on both Knot and Pod, including different versions of R.

## Loading R

To load R, enter one of the commands

```
# Knot
R
```
or
```
# Pod
load module R
R
```

To exit, enter `q()`.

Note that the RStudio IDE is not available for use on the clusters.

*Remember: Most analyses should be performed on compute nodes by submitting jobs. The login node should only be used for simple analyses, testing, or debugging.*

## Versions

On Pod, the available versions of R include

```
R/3.2.2
R/3.4.4
R/3.5.1-multith
R/3.5.1
```

The default is the latest version. To load a specific version, for example, enter `load module R/3.4.4`.

On Knot, the available version of R is 3.2.2.

A different version of R can be installed inside your home directory. For more info see <http://csc.cnsi.ucsb.edu/docs/using-r-knot-braid-and-pod>.

## Packages

To see a list of already installed R packages and their versions, use the R command `installed.packages()`. Additional packages can be installed using the R command `install.packages("package")` and should be stored inside your home folder. When using this command you may be prompted to select a CRAN mirror from which to download; select a USA (CA) mirror with an HTTPS connection for a fast and secure download. R should automatically add the home-based library to `.libPaths()` (enter to confirm), which allows it to detect packages installed inside your home folder.

## Example job files

### Knot

```
#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -m be
#PBS -M user@ucsb.edu

cd $PBS_O_WORKDIR

Rscript script.R
```

### Pod

```
#!/bin/bash -l
#SBATCH --nodes=1 --ntasks-per-node=1
#SBATCH --mail-type=ALL
#SBATCH --mail-user=user@ucsb.edu

cd $SLURM_SUBMIT_DIR

module load R
Rscript script.R
```
